### ISSUE TITLE
When to reset a counter

### ISSUE THREAD

**Issue by nemo83** [fiadliel/prometheus_client_scala#2]
Currently counters are not reset when the metric is read from the `Registry` and published, so I'm not sure how to display a RPM metric.

Am I missing something?

I may suggest to have some sort of Resettable and Unbounded Counters.

Formers are reset to 0 every time they are read, the latter will grow indefinitely.

**Comment by fiadliel** [comment]
A counter is a monotonically increasing value, though it may be reset occasionally (usually due to server restart). This is by design.

If you have a metric that is requests-per-minute, and you want to aggregate this across multiple servers, the data is vulnerable to incorrect behaviour in the presence of missing scrapes, skews in data request time, etc.

Instead, the general approach is to have a metric representing the number of requests. You can sum this across servers, and the request rate can be calculated using a function, usually `rate` which smooths the data over a period of time: https://prometheus.io/docs/querying/functions/#rate() or `irate` which gives the most recent change, but may be spiky: https://prometheus.io/docs/querying/functions/#irate()

Not planning to change anything here, a resettable counter would encourage approaches to monitoring which would be unreliable.
